<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<NoWarn>NU1701</NoWarn>
	<UserSecretsId>003c9104-e2ae-48c4-8c59-f74d6726f500</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\login-signupPhoto.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CareConnect.Model\CareConnect.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\login-signupPhoto.jpg" />
  </ItemGroup>

</Project>
